apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
data:
  AWS_ACCESS_KEY_ID: YWNjZXNza2V5
  AWS_SECRET_ACCESS_KEY: c2VjcmV0a2V5

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: taskconsumer-triggerauth
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: aws-secrets
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: aws-secrets
      key: AWS_SECRET_ACCESS_KEY

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: taskconsumer-scaler
spec:
  scaleTargetRef:
    name: taskconsumer
  pollingInterval: 5
  cooldownPeriod: 5
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 5
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: taskconsumer-triggerauth
      metadata:
        queueURL: http://localstack.default:4566/000000000000/task-queue
        awsEndpoint: http://localstack.default:4566
        queueLength: "50"
        awsRegion: "eu-west-1"
        identityOwner: pod