apiVersion: apps/v1
kind: Job
metadata:
  name: taskproducer
spec:
  template:
    spec:
      containers:
        - name: taskproducer
          image: taskproducer:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 3
